Update hosts.txt
Clefspeare13/pornhosts pull request #349
Opened 2021-04-06 07:50 UTC by FlyingBackdoor

Added some new and proxy domains

2021-04-19 13:19 UTC, spirillen requested changes

2021-04-19 13:19 UTC, spirillen commented on submit_here/hosts.txt
> +#Submission
Invalid Line...

It is absolutely a long list (Bulk) but without individual proof, this PR will be awaiting for @Clefspeare13 

Best alternative is you submit each one as issues here: <https://www.mypdns.org/maniphest/task/edit/form/2/>

With screenshots....

2021-04-24 07:25 UTC, FlyingBackdoor reviewed
Removed Invalid line

2021-05-19 19:16 UTC, closed without merging

2021-05-31 12:29 UTC, spirillen commented on submit_here/hosts.txt
> +www.porndude.me
https://www.mypdns.org/T1923

2021-05-31 12:37 UTC, spirillen commented on submit_here/hosts.txt
> +indian-xnxx.pro
https://www.mypdns.org/T4429

2021-05-31 12:49 UTC, spirillen commented on submit_here/hosts.txt
> +xnxxmommy.com
https://www.mypdns.org/T4430

2021-05-31 12:51 UTC, spirillen commented on submit_here/hosts.txt
> +xnxx123.org
https://www.mypdns.org/T4431

2021-05-31 12:55 UTC, spirillen commented on submit_here/hosts.txt
> +xnxxporn.top
https://www.mypdns.org/T4432

2021-05-31 12:58 UTC, spirillen commented on submit_here/hosts.txt
> +xnxxporn.video
https://www.mypdns.org/T4433

2021-05-31 13:00 UTC, spirillen commented on submit_here/hosts.txt
> +xnxxvideos.fun
https://www.mypdns.org/T4434

2021-05-31 13:11 UTC, spirillen commented on submit_here/hosts.txt
> +xnxx-films.com
https://www.mypdns.org/T4435

2021-05-31 13:14 UTC, spirillen commented on submit_here/hosts.txt
> +xnxxx.rocks
https://www.mypdns.org/T4436

2021-05-31 13:24 UTC, spirillen commented on submit_here/hosts.txt
> +www.xnxx.report
https://www.mypdns.org/T4437

2021-05-31 13:28 UTC, spirillen commented on submit_here/hosts.txt
> +xnxxbest.pro
https://www.mypdns.org/T4438

2021-05-31 13:35 UTC, spirillen commented on submit_here/hosts.txt
> +xnxx-best.com
Needs the `www.$domain`

https://www.mypdns.org/T4439

2021-05-31 13:37 UTC, spirillen commented on submit_here/hosts.txt
> +xnxx.sexy
https://www.mypdns.org/T4440

2021-05-31 13:56 UTC, spirillen commented on submit_here/hosts.txt
> +xnxx.news
https://www.mypdns.org/T4445

2021-05-31 14:01 UTC, spirillen commented on submit_here/hosts.txt
> +xnnx.name
https://www.mypdns.org/T4446

2021-05-31 14:10 UTC, spirillen commented on submit_here/hosts.txt
> +xnxx.college
https://www.mypdns.org/T4447

2021-05-31 14:16 UTC, spirillen commented on submit_here/hosts.txt
> +xnxxhd.biz
https://www.mypdns.org/T4448

2021-05-31 14:21 UTC, spirillen commented on submit_here/hosts.txt
> +www.xxnx.bike
https://www.mypdns.org/T4450

2021-05-31 14:58 UTC, spirillen commented on submit_here/hosts.txt
> +xhamster7.desi
https://www.mypdns.org/T4451

I have also added `xhamster{1..11}.desi`

2021-05-31 15:01 UTC, spirillen commented on submit_here/hosts.txt
> +www.porn-xnxx.com
https://www.mypdns.org/T4461

2021-05-31 15:09 UTC, spirillen commented on submit_here/hosts.txt
> +www.pornmd.com
https://www.mypdns.org/T1445

2021-05-31 15:12 UTC, spirillen commented on submit_here/hosts.txt
> +www.thepornlist.net
https://www.mypdns.org/T4462

2021-05-31 15:14 UTC, spirillen commented on submit_here/hosts.txt
> +porndudecasting.com
https://www.mypdns.org/T4463

2021-05-31 15:17 UTC, spirillen commented on submit_here/hosts.txt
> +pornlistdude.com
https://www.mypdns.org/T4464

2021-05-31 15:19 UTC, spirillen commented on submit_here/hosts.txt
> +xfantazy.com
https://www.mypdns.org/T4465

2021-05-31 15:25 UTC, spirillen commented on submit_here/hosts.txt
> +www.dinotube.com
https://www.mypdns.org/T4466

2021-05-31 15:33 UTC, spirillen commented on submit_here/hosts.txt
> +porndude.xyz
https://www.mypdns.org/T4468

2021-05-31 15:41 UTC, spirillen commented on submit_here/hosts.txt
> +www.thepornlist.net
https://www.mypdns.org/T4462

2021-05-31 15:43 UTC, spirillen commented on submit_here/hosts.txt
> +teenxnxx.cc
https://www.mypdns.org/T4470

2021-05-31 15:46 UTC, spirillen commented on submit_here/hosts.txt
> +theporndude.vip
https://www.mypdns.org/T4471

2021-05-31 15:48 UTC, spirillen commented on submit_here/hosts.txt
> +mrporndude.com
https://www.mypdns.org/T4472

2021-05-31 15:51 UTC, spirillen commented on submit_here/hosts.txt
> +xlxx.space
https://www.mypdns.org/T4473